<?php

declare(strict_types=1);

namespace ArnaudMoncondhuy\SynapseBundle\DependencyInjection;

use Symfony\Component\Config\Definition\Builder\TreeBuilder;
use Symfony\Component\Config\Definition\ConfigurationInterface;

/**
 * Définition de l'arbre de configuration du Bundle.
 *
 * Ce fichier valide et documente les options disponibles dans le fichier `config/packages/synapse.yaml`.
 *
 * Exemple de configuration attendue :
 * synapse:
 *    model: 'gemini-2.5-flash'
 *    vertex:
 *        project_id: 'your-gcp-project-id'
 *        region: 'europe-west1'
 *        service_account_json: '%kernel.project_dir%/config/secrets/gcp-service-account.json'
 *    thinking:
 *        enabled: true
 *        budget: 2048
 *    safety_settings:
 *        enabled: false
 *        default_threshold: 'BLOCK_MEDIUM_AND_ABOVE'
 *        thresholds:
 *            hate_speech: 'BLOCK_MEDIUM_AND_ABOVE'
 *            dangerous_content: 'BLOCK_MEDIUM_AND_ABOVE'
 *            harassment: 'BLOCK_MEDIUM_AND_ABOVE'
 *            sexually_explicit: 'BLOCK_MEDIUM_AND_ABOVE'
 *    generation_config:
 *        temperature: 1.0
 *        top_p: 0.95
 *        top_k: 40
 *        max_output_tokens: null
 *        stop_sequences: []
 *    context_caching:
 *        enabled: false
 *        cached_content_id: null
 */
class Configuration implements ConfigurationInterface
{
    public function getConfigTreeBuilder(): TreeBuilder
    {
        $treeBuilder = new TreeBuilder('synapse');

        $treeBuilder->getRootNode()
            ->children()
            ->scalarNode('model')
            ->defaultValue('gemini-2.5-flash')
            ->info('Le modèle Gemini à utiliser via Vertex AI (défaut: gemini-2.5-flash).')
            ->end()
            ->scalarNode('personas_path')
            ->defaultNull()
            ->info('Chemin absolu vers votre fichier personas.json personnalisé. Si null, utilise le fichier par défaut du bundle.')
            ->end()
            ->arrayNode('thinking')
            ->addDefaultsIfNotSet()
            ->children()
                ->booleanNode('enabled')
                    ->defaultTrue()
                    ->info('Activer le mode thinking natif de Gemini (améliore le debug)')
                ->end()
                ->integerNode('budget')
                    ->defaultValue(1024)
                    ->min(0)
                    ->max(24576)
                    ->info('Budget de tokens pour le thinking (0 = désactivé si supporté par le modèle)')
                ->end()
            ->end()
            ->end()
            ->arrayNode('vertex')
            ->addDefaultsIfNotSet()
            ->children()
                ->scalarNode('project_id')
                    ->isRequired()
                    ->cannotBeEmpty()
                    ->info('Google Cloud Project ID (obligatoire)')
                ->end()
                ->scalarNode('region')
                    ->defaultValue('europe-west1')
                    ->info('Région Vertex AI (europe-west1, us-central1, etc.)')
                ->end()
                ->scalarNode('service_account_json')
                    ->isRequired()
                    ->cannotBeEmpty()
                    ->info('Chemin vers le fichier JSON du service account Google Cloud (obligatoire)')
                ->end()
            ->end()
            ->end()
            ->arrayNode('safety_settings')
            ->addDefaultsIfNotSet()
            ->children()
                ->booleanNode('enabled')
                    ->defaultFalse()
                    ->info('Activer le filtrage de sécurité du contenu (safety filters)')
                ->end()
                ->scalarNode('default_threshold')
                    ->defaultValue('BLOCK_MEDIUM_AND_ABOVE')
                    ->info('Seuil par défaut : BLOCK_LOW_AND_ABOVE, BLOCK_MEDIUM_AND_ABOVE, BLOCK_ONLY_HIGH, BLOCK_NONE')
                ->end()
                ->arrayNode('thresholds')
                    ->addDefaultsIfNotSet()
                    ->children()
                        ->scalarNode('hate_speech')
                            ->defaultValue('BLOCK_MEDIUM_AND_ABOVE')
                            ->info('Seuil pour hate_speech (discours haineux)')
                        ->end()
                        ->scalarNode('dangerous_content')
                            ->defaultValue('BLOCK_MEDIUM_AND_ABOVE')
                            ->info('Seuil pour dangerous_content (contenu dangereux)')
                        ->end()
                        ->scalarNode('harassment')
                            ->defaultValue('BLOCK_MEDIUM_AND_ABOVE')
                            ->info('Seuil pour harassment (harcèlement)')
                        ->end()
                        ->scalarNode('sexually_explicit')
                            ->defaultValue('BLOCK_MEDIUM_AND_ABOVE')
                            ->info('Seuil pour sexually_explicit (contenu sexuel explicite)')
                        ->end()
                    ->end()
                ->end()
            ->end()
            ->end()
            ->arrayNode('generation_config')
            ->addDefaultsIfNotSet()
            ->children()
                ->floatNode('temperature')
                    ->defaultValue(1.0)
                    ->min(0.0)
                    ->max(2.0)
                    ->info('Température (0.0 = déterministe, 2.0 = créatif)')
                ->end()
                ->floatNode('top_p')
                    ->defaultValue(0.95)
                    ->min(0.0)
                    ->max(1.0)
                    ->info('Top-P pour nucleus sampling (0.0 à 1.0)')
                ->end()
                ->integerNode('top_k')
                    ->defaultValue(40)
                    ->min(1)
                    ->info('Top-K (nombre de tokens à considérer)')
                ->end()
                ->integerNode('max_output_tokens')
                    ->defaultNull()
                    ->info('Nombre maximum de tokens de sortie (null = par défaut du modèle)')
                ->end()
                ->arrayNode('stop_sequences')
                    ->prototype('scalar')->end()
                    ->defaultValue([])
                    ->info('Séquences d\'arrêt personnalisées')
                ->end()
            ->end()
            ->end()
            ->arrayNode('context_caching')
            ->addDefaultsIfNotSet()
            ->children()
                ->booleanNode('enabled')
                    ->defaultFalse()
                    ->info('Activer le context caching pour réduire les tokens et les coûts')
                ->end()
                ->scalarNode('cached_content_id')
                    ->defaultNull()
                    ->info('ID du contenu en cache créé via l\'API Vertex AI')
                ->end()
            ->end()
            ->end()
            // ========== NOUVELLES CONFIGURATIONS (Refonte) ==========
            ->arrayNode('persistence')
            ->addDefaultsIfNotSet()
            ->children()
                ->booleanNode('enabled')
                    ->defaultFalse()
                    ->info('Activer la persistence des conversations en base de données')
                ->end()
                ->scalarNode('handler')
                    ->defaultValue('session')
                    ->info('Handler de persistence : "session" (défaut) ou "doctrine"')
                ->end()
                ->scalarNode('conversation_class')
                    ->defaultNull()
                    ->info('FQCN de l\'entité Conversation concrète (ex : App\Module\Assistant\Entity\Conversation)')
                ->end()
                ->scalarNode('message_class')
                    ->defaultNull()
                    ->info('FQCN de l\'entité Message concrète (ex : App\Module\Assistant\Entity\Message)')
                ->end()
            ->end()
            ->end()
            ->arrayNode('encryption')
            ->addDefaultsIfNotSet()
            ->children()
                ->booleanNode('enabled')
                    ->defaultFalse()
                    ->info('Activer le chiffrement des conversations (libsodium AES-256-GCM)')
                ->end()
                ->scalarNode('key')
                    ->defaultNull()
                    ->info('Clé de chiffrement (32 bytes, ex: %env(SYNAPSE_ENCRYPTION_KEY)%)')
                ->end()
            ->end()
            ->end()
            ->arrayNode('token_tracking')
            ->addDefaultsIfNotSet()
            ->children()
                ->booleanNode('enabled')
                    ->defaultFalse()
                    ->info('Activer le tracking des tokens et calcul des coûts')
                ->end()
                ->arrayNode('pricing')
                    ->useAttributeAsKey('model')
                    ->arrayPrototype()
                        ->children()
                            ->floatNode('input')->end()
                            ->floatNode('output')->end()
                        ->end()
                    ->end()
                    ->info('Tarifs par modèle ($/1M tokens) ex: gemini-2.5-flash: {input: 0.30, output: 2.50}')
                ->end()
            ->end()
            ->end()
            ->arrayNode('risk_detection')
            ->addDefaultsIfNotSet()
            ->children()
                ->booleanNode('enabled')
                    ->defaultFalse()
                    ->info('Activer le système "Ange Gardien" (détection de risques)')
                ->end()
                ->booleanNode('auto_register_tool')
                    ->defaultTrue()
                    ->info('Enregistrer automatiquement ReportRiskTool')
                ->end()
            ->end()
            ->end()
            ->arrayNode('retention')
            ->addDefaultsIfNotSet()
            ->children()
                ->integerNode('days')
                    ->defaultValue(30)
                    ->min(1)
                    ->info('Durée de rétention RGPD (jours)')
                ->end()
            ->end()
            ->end()
            ->arrayNode('security')
            ->addDefaultsIfNotSet()
            ->children()
                ->scalarNode('permission_checker')
                    ->defaultValue('default')
                    ->info('Stratégie de vérification des permissions : "default" (DefaultPermissionChecker), "none" (pas de vérification), ou service ID personnalisé')
                ->end()
                ->scalarNode('admin_role')
                    ->defaultValue('ROLE_ADMIN')
                    ->info('Rôle Symfony requis pour accéder à l\'admin et voir toutes les conversations')
                ->end()
            ->end()
            ->end()
            ->arrayNode('context')
            ->addDefaultsIfNotSet()
            ->children()
                ->scalarNode('provider')
                    ->defaultValue('default')
                    ->info('Fournisseur de contexte : "default" (DefaultContextProvider), "user_aware" (UserAwareContextProvider), ou service ID personnalisé')
                ->end()
                ->scalarNode('language')
                    ->defaultValue('fr')
                    ->info('Langue par défaut pour les prompts système (fr, en)')
                ->end()
                ->scalarNode('base_identity')
                    ->defaultNull()
                    ->info('Identité de base personnalisée (override la valeur par défaut)')
                ->end()
            ->end()
            ->end()
            ->arrayNode('admin')
            ->addDefaultsIfNotSet()
            ->children()
                ->booleanNode('enabled')
                    ->defaultFalse()
                    ->info('Activer l\'interface d\'administration')
                ->end()
                ->scalarNode('route_prefix')
                    ->defaultValue('/synapse/admin')
                    ->info('Préfixe des routes admin')
                ->end()
                ->scalarNode('default_color')
                    ->defaultValue('#8b5cf6')
                    ->info('Couleur par défaut du module (hex)')
                ->end()
                ->scalarNode('default_icon')
                    ->defaultValue('robot')
                    ->info('Icône par défaut du module')
                ->end()
            ->end()
            ->end()
            ->arrayNode('ui')
            ->addDefaultsIfNotSet()
            ->children()
                ->booleanNode('sidebar_enabled')
                    ->defaultTrue()
                    ->info('Activer la sidebar (historique conversations)')
                ->end()
                ->scalarNode('layout_mode')
                    ->defaultValue('standalone')
                    ->info('Mode de layout admin : "standalone" (avec sidebar) ou "module" (intégration dans module_base.html.twig)')
                ->end()
            ->end()
            ->end()
            ->end();

        return $treeBuilder;
    }
}
