<?php

declare(strict_types=1);

namespace ArnaudMoncondhuy\SynapseBundle\Contract;

/**
 * Interface for logging Synapse LLM exchanges.
 *
 * Implementations can persist debug information to different backends:
 * - Monolog: logs to files
 * - Doctrine: logs to database
 * - Elasticsearch: logs to external service
 *
 * This interface allows flexible debug logging strategy without coupling ChatService to a specific backend.
 */
interface SynapseDebugLoggerInterface
{
    /**
     * Log an LLM exchange with metadata and full payload.
     *
     * @param string $debugId         Unique identifier for this exchange (generated by caller)
     * @param array  $metadata        Lightweight metadata (model, provider, token usage, created_at)
     * @param array  $rawPayload      Full request/response payload (can be very large)
     */
    public function logExchange(string $debugId, array $metadata, array $rawPayload): void;

    /**
     * Retrieve logged exchange by debug ID.
     *
     * @return array|null Full debug data, or null if not found
     */
    public function findByDebugId(string $debugId): ?array;
}
